$ANSIBLE_VAULT;1.1;AES256
31313631616131313332316131313637366338376366623134336464643261636335376337626536
3530363138393763313737623533313138366264616562390a376235616235386639393630633465
61626266316165336163313133373339343164343263633661303366373033653061313130346163
6631623633386132300a363530633234346430306633383537373464343833363230313562663135
36386130653961663335643537373665313939666165363031643732376437653565643131396636
61636535373762646239396538326639326638346537653662353065316135356238373835373732
61326233656265633531376436393337636530336230306265333530363764623465386534396362
35373339653538653964396234323931323235343664333365313735613761646137623939646462
65343639313133653134376337616232626436323131393666613364613534333738393064383033
62356266393838343065313537313635326630666162356161363730363932343462396139363239
65633238353761653361316332363432643031316331336535386331323033313666376334313531
38386636313865316337323239353738306265386363643833343564383765356534333366346531
38636234666566653432396664623838666665393335356332303762303362306561313866363763
39333930393766663162613335333131376430393962643833613433646162363139393964306561
65646532613765333463633665393936313637333565363162356666653365383263633035313165
33343965616565663130616138333034653464623333616164633237666532363161303864363961
36383139343936303334336366373564336139313332653638326134346162356537363530623639
36363230623130663962626663346635633936336566623430616363653035373365326334616332
363230336138393737333839316235623666
